# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_auto_20170303_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='link',
            field=models.TextField(default='www.twitter.com'),
            preserve_default=False,
        ),
    ]
