# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0004_auto_20170306_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Feed.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hit',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
