# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pulse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='author',
            field=models.CharField(default='Mike Stone', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hit',
            name='title',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hit',
            name='key_words',
            field=models.CharField(max_length=100),
        ),
    ]
