# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pulse', '0003_auto_20170303_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit',
            name='time_pub',
        ),
        migrations.AlterField(
            model_name='hit',
            name='date_pub',
            field=models.DateTimeField(),
        ),
    ]
