# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pulse', '0007_remove_hit_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='source_type',
            field=models.CharField(default='professional', max_length=15),
            preserve_default=False,
        ),
    ]
